### ISSUE TITLE
CSS bug

### ISSUE THREAD

**Issue by AryanshSourcefuse** [sourcefuse/workflows-creator#18]
**Describe the bug**
The popover, which is used for selecting items like column changes or intervals, is initially appearing far to the right of the anchor element. However, upon resizing the screen, it correctly repositions itself relative to the anchor element, but this adjustment sometimes causes overlapping issues on other components.

**To Reproduce**
1. Go to workflow-creator
2. Click on `When this happens`
3. Resize the window

**Screenshots**
<img width="1279" alt="Screenshot 2023-08-07 at 4 01 02 PM" src="https://github.com/sourcefuse/workflows-creator/assets/121281459/36bad570-30da-4649-a228-f49df237426f">
<img width="805" alt="Screenshot 2023-08-07 at 4 07 01 PM" src="https://github.com/sourcefuse/workflows-creator/assets/121281459/2fefd482-cf84-44dd-ab62-0f48f511590f">

**Additional context**
I am using web component in React.

**Comment by AryanshSourcefuse** [comment]
An Update: Seems like popup appearing far right is because of new chrome update as it looks good in different browser. But overlapping issue still exists.

**Comment by yeshamavani** [comment]
@Deepika516 what is pending in this

**Comment by Deepika516** [comment]
> @Deepika516 what is pending in this

Both are Done the 1st one is CSS issue Because of chrome update 2nd is overlapping issue i corrected that too , we can close this issue

**Comment by yeshamavani** [comment]
Can you add link to the PR

**Comment by Deepika516** [comment]
> Can you add link to the PR

 linked the PR ..

**Comment by yeshamavani** [comment]
https://github.com/sourcefuse/workflows-creator/pull/31
will be closed once merged
