### ISSUE TITLE
Unable to add input values in Workflow. 

### ISSUE THREAD

**Issue by Deepika516** [sourcefuse/workflows-creator#22]
**Describe the bug**
1. Unable to add input values Whenever i click on input ,the popper hides.

**To Reproduce**
1. Go to workflow library, and try adding a workflow
2. Select Text field,interval,email,number and see it opens n hides the popups suddendly

**Expected behavior**
1. User should be able to add input values 
2.  On opening a new popup ,previous popup's should close,

**Screenshots**

https://github.com/sourcefuse/workflows-creator/assets/109737499/a5a851ae-6d2d-403a-850d-051ca746a121

**Additional context**

**Comment by AryanshSourcefuse** [comment]
Got it fixed, It was some css bug when web-component was rendered at the same time, a modal is rendered.
