### ISSUE TITLE
Support for adding templates in React

### ISSUE THREAD

**Issue by AryanshSourcefuse** [sourcefuse/workflows-creator#27]
While using workflow-creator, I want to configure workflow so that if task is added, default startDate should be added by workflow.
When `date` is selected in `workflow-creator`, Input field is not appearing, while checking in angular(rakuten) code. A template map is passed to render particular template for particular cases which is `date` in this case.

I want to do the same with React, but I'm not able to figure out, how to render in React as there's no concept to `templates` in React or Vanilla JS
<img width="1137" alt="Screenshot 2023-09-05 at 8 17 06 PM" src="https://github.com/sourcefuse/workflows-creator/assets/121281459/4dc967f2-0f93-46b6-8d67-8b6133fefe4a">

**Comment by AryanshSourcefuse** [comment]
https://github.com/sourcefuse/rakuten-pms-ui/blob/ea085145934d14b65f7c03189c7d9d41d76f6cd1/src/app/main/workspace/main-view/main-board/components/workflows-dialog/workflow-editor-dialog/workflow-editor-dialog.component.ts#L182

Here it is configured in rakuten pms. @arpit1503khanna

**Comment by AryanshSourcefuse** [comment]
Currently @arpit1503khanna added default date picker and current one is working.
But I believe we will be getting requirement to customise the input fields(text, date etc..)

So, it will be nice if there could be anyway to customise input elements in React, just like we do it angular with ng-templates.

**Comment by arpit1503khanna** [comment]
Also referencing to this issue
https://github.com/sourcefuse/workflows-creator/issues/24

**Comment by AryanshSourcefuse** [comment]
Hi @yeshamavani 
This issue is not fixed yet
