### ISSUE TITLE
Workflow creator (angular) is not working

### ISSUE THREAD

**Issue by Pushpak562** [sourcefuse/workflows-creator#37]
- [x] People` column blocker 
- [x] Text column blocker got fixed
- [x] Workflow creator is not working  issue was in it's dependency management - need to upgrade the angular version
- [x] CSS problem with popup 
- [ ] documentation is working on better documentation - @GurpreetChhabraSF

**Comment by yeshamavani** [comment]
@Deepika516 what all is pending here 
can you please close this

**Comment by Deepika516** [comment]
The changes was in the project not in Library , so No PR Raised for this .It's Done
