### ISSUE TITLE
'Invalid Date' is shown when no time is selected for column 'Date/Time' in worklfow

### ISSUE THREAD

**Issue by arpit1503khanna** [sourcefuse/workflows-creator#40]
**Describe the bug**
'Invalid Date' is shown when no time is selected for column 'Date/Time' in worklfow

 More information can be seen here: 
 https://sourcefuse.atlassian.net/browse/OPX-9056

**Comment by yeshamavani** [comment]
In this dont hard code the time or date 
make it configurable
