### ISSUE TITLE
Issues in "Date column & Datetime column" for Something section in "Add Check Value" event

### ISSUE THREAD

**Issue by arpit1503khanna** [sourcefuse/workflows-creator#45]
**Describe the bug**
Issues in "Date column & Datetime column" for Something section in "Add Check Value" event

For further information refer to the link below:
https://sourcefuse.atlassian.net/browse/OPX-9080

**Comment by yeshamavani** [comment]
@arpit1503khanna any updates on this.. please update the status accordingly

**Comment by yeshamavani** [comment]
@arpit1503khanna any updates on this..
is this resolved or still pending ?

**Comment by arpit1503khanna** [comment]
> @arpit1503khanna any updates on this.. is this resolved or still pending ?

Yes
